### ISSUE TITLE
Makefileの作成

### ISSUE THREAD

**Issue by kkiyama117** [Zoniisan/penguin#4]
## モチベーション
envファイルのコピーやDockerコマンドの起動をより簡潔に行いたい.

## 説明
幾つか方法がある.
1. [Makefile](https://docs.python-guide.org/writing/structure/#makefile)
2. Python script
    1. setup.pyのCmdで[Scriptの実行](https://docs.python.org/ja/3/distutils/extending.html) 
    2. pipenvのPipfileに[コマンドを書く](https://pipenv-ja.readthedocs.io/ja/translate-ja/advanced.html#custom-script-shortcuts)

今回, 実行するコマンドがほとんどPythonのScriptでない事や, Pipenv非導入な事を考慮し,Makefileでの実装を提案する.

## 備考
`<!-- -->` でこの備考の欄の説明とかをコメントにしておくといちいち消さずに済んでいいかも.

**Comment by kkiyama117** [comment]
上記どの手段を取るかわからないのでとりあえずIssue立てるまでにしておきます.
方針が決まった上でやれと言われたらPullRequest出します.

**Comment by Zoniisan** [comment]
@kkiyama117 
コメントありがとうございます。以後よろしくお願いいたします。

PR #6 において

1. `make` でローカル環境向けの環境変数ファイルをコピーし、
1. `make start` で検証用サーバーを起動

ってできるようにしてみました。こんな感じで良いのでしょうか……
（初心者ですいません）

## 参考サイト
Makefileの解説
http://omilab.naist.jp/~mukaigawa/misc/Makefile.html

**Comment by kkiyama117** [comment]
僭越ながらPull Requestの方でReviewさせていただきました.大体いい感じだと思います.
